source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '8.0'

target 'BSImagePickerExample'
  pod "BSImagePicker", :path => "../"
end

target 'BSImagePickerObjectiveCExample'
  pod "BSImagePicker", :path => "../"
end

target 'BSImagePickerExampleTests'
  pod "BSImagePicker", :path => "../"
end

